# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/bsdo/project/python/BSTrade/BSTrade/Component/View/Ui/ui_mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 522)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.exchangeNameLb = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.exchangeNameLb.setFont(font)
        self.exchangeNameLb.setObjectName("exchangeNameLb")
        self.verticalLayout_6.addWidget(self.exchangeNameLb)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_3.setSpacing(5)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.rateLimitTbox = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rateLimitTbox.sizePolicy().hasHeightForWidth())
        self.rateLimitTbox.setSizePolicy(sizePolicy)
        self.rateLimitTbox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.rateLimitTbox.setReadOnly(True)
        self.rateLimitTbox.setObjectName("rateLimitTbox")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.rateLimitTbox)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.cntChk = QtWidgets.QCheckBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cntChk.sizePolicy().hasHeightForWidth())
        self.cntChk.setSizePolicy(sizePolicy)
        self.cntChk.setText("")
        self.cntChk.setCheckable(False)
        self.cntChk.setTristate(False)
        self.cntChk.setObjectName("cntChk")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cntChk)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.utcLb = QtWidgets.QLabel(self.groupBox)
        self.utcLb.setText("")
        self.utcLb.setObjectName("utcLb")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.utcLb)
        self.verticalLayout_6.addLayout(self.formLayout_3)
        self.funcBtn = QtWidgets.QWidget(self.groupBox)
        self.funcBtn.setObjectName("funcBtn")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.funcBtn)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.screenBtn = QtWidgets.QPushButton(self.funcBtn)
        self.screenBtn.setObjectName("screenBtn")
        self.horizontalLayout_3.addWidget(self.screenBtn)
        self.accountBtn = QtWidgets.QPushButton(self.funcBtn)
        self.accountBtn.setObjectName("accountBtn")
        self.horizontalLayout_3.addWidget(self.accountBtn)
        self.orderBtn = QtWidgets.QPushButton(self.funcBtn)
        self.orderBtn.setObjectName("orderBtn")
        self.horizontalLayout_3.addWidget(self.orderBtn)
        self.verticalLayout_6.addWidget(self.funcBtn)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.symbol = QtWidgets.QWidget(self.centralwidget)
        self.symbol.setObjectName("symbol")
        self.symbol_layout = QtWidgets.QHBoxLayout(self.symbol)
        self.symbol_layout.setContentsMargins(0, 0, 0, 0)
        self.symbol_layout.setSpacing(0)
        self.symbol_layout.setObjectName("symbol_layout")
        self.symGrpBox = QtWidgets.QGroupBox(self.symbol)
        self.symGrpBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.symGrpBox.setFlat(False)
        self.symGrpBox.setObjectName("symGrpBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.symGrpBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout.setRowWrapPolicy(QtWidgets.QFormLayout.DontWrapRows)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout.setSpacing(5)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.symGrpBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.volumeTbox = QtWidgets.QLineEdit(self.symGrpBox)
        self.volumeTbox.setObjectName("volumeTbox")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.volumeTbox)
        self.label_3 = QtWidgets.QLabel(self.symGrpBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.priceTbox = QtWidgets.QLineEdit(self.symGrpBox)
        self.priceTbox.setObjectName("priceTbox")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.priceTbox)
        self.label_4 = QtWidgets.QLabel(self.symGrpBox)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.chgPerTbox = QtWidgets.QLineEdit(self.symGrpBox)
        self.chgPerTbox.setObjectName("chgPerTbox")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.chgPerTbox)
        self.label_6 = QtWidgets.QLabel(self.symGrpBox)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.chgTbox = QtWidgets.QLineEdit(self.symGrpBox)
        self.chgTbox.setObjectName("chgTbox")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.chgTbox)
        self.label_5 = QtWidgets.QLabel(self.symGrpBox)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.vol24Tbox = QtWidgets.QLineEdit(self.symGrpBox)
        self.vol24Tbox.setFrame(True)
        self.vol24Tbox.setObjectName("vol24Tbox")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.vol24Tbox)
        self.nameTbox = QtWidgets.QLineEdit(self.symGrpBox)
        self.nameTbox.setObjectName("nameTbox")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.nameTbox)
        self.label = QtWidgets.QLabel(self.symGrpBox)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setObjectName("label")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label)
        self.verticalLayout_5.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton = QtWidgets.QPushButton(self.symGrpBox)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_4.addWidget(self.pushButton)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.symbol_layout.addWidget(self.symGrpBox)
        self.verticalLayout_2.addWidget(self.symbol)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BSTrade"))
        self.groupBox.setTitle(_translate("MainWindow", "Exchange"))
        self.exchangeNameLb.setText(_translate("MainWindow", "Exchange Name"))
        self.label_7.setText(_translate("MainWindow", "RateLimit"))
        self.label_8.setText(_translate("MainWindow", "Connected"))
        self.label_9.setText(_translate("MainWindow", "UTC"))
        self.screenBtn.setText(_translate("MainWindow", "Screener"))
        self.accountBtn.setText(_translate("MainWindow", "Account"))
        self.orderBtn.setText(_translate("MainWindow", "Order"))
        self.symGrpBox.setTitle(_translate("MainWindow", "Symbol"))
        self.label_2.setText(_translate("MainWindow", "Volume"))
        self.label_3.setText(_translate("MainWindow", "Price"))
        self.label_4.setText(_translate("MainWindow", "24h CHG%"))
        self.label_6.setText(_translate("MainWindow", "24h CHG"))
        self.label_5.setText(_translate("MainWindow", "24h Vol"))
        self.label.setText(_translate("MainWindow", "Name"))
        self.pushButton.setText(_translate("MainWindow", "Chart"))

